---

- name: Prepare the servers for install ceph
  hosts: ceph
  become: yes
  become_method: sudo
  gather_facts: True

  vars_files:
    - group_vars/ceph.yml

  roles:
    - pre-provision
    - provision-user
    - provision-stack